model: compositional
criterion: ctc
feat_size: 40
hidden_size: 640
pos_only: true
lang_size: 39
proj_size: 0
layer_size: 5
lr_rate: 0.1
l2: 0
langs: ['eng', 'cmn', 'deu', 'fra', 'ita', 'rus', 'tur', 'vie']
criterion: ctc
input_size: 40
in_channel: 1
mid_channel: 64
out_channel: 128
kernel_size: [[3,3],[3,3]]
stride: [2, 2]
dropout: 0.0
act_func_type: relu
front_end_layer_norm: False
hidden_size: 256
head_size: 4
d_ff: 2048
block_size: 12
lang_size: 39
pos_dropout: 0.0
slf_attn_dropout: 0.0
ffn_dropout: 0.0
residual_dropout: 0.1
normalize_before: false,
concat_after: false
relative_positional: false
activation: glu
